### ISSUE TITLE
Problem after update from 1.0.42 to 1.0.43

### ISSUE THREAD

**Issue by felixdrp** [GoogleChromeLabs/ndb#239]
It start after update from 1.0.42 to 1.0.43
I tried to downgrade later but the error persist.
Remove and install again does not work.

### Steps to reproduce

**Tell us about your environment:**

* ndb version:
update from 1.0.42 to 1.0.43
I tried to downgrade later but the error persist.
* Platform / OS version:
Linux pop-os 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Node.js version:
node 8 and node 11
**What steps will reproduce the problem?**
ndb
_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**
![ndb not working after update to 1 0 43](https://user-images.githubusercontent.com/8149900/52947376-6545c080-336e-11e9-9e93-fd8f27911002.png)

**Comment by felixdrp** [comment]
Start working today after apt update.

**Comment by felixdrp** [comment]
-  If **Chrome is open** ndb **fails**.
-  If **Chrome is closed** ndb **works**.

ndb "works" if Chrome is not already open.

**Comment by chenxq** [comment]
I have the same problem in both 1.0.42 and 1.0.43.
And ndb fails no matter Chrome is opened nor closed.

**Comment by ak239** [comment]
Should be fixed in latest ndb (1.0.44). Feel free to file another issue if you still can reproduce it and thanks for your report!

**Comment by felixdrp** [comment]
I updated to ndb (1.0.44)... the error persisted. The only difference is that now I have an error message:
ndb
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

If I close the Chrome browser it works...

**Comment by Manikanta-Gandham** [comment]
ndb:1.0.44
node: 10.15.3. 
Doesn't work even when the chrome browser is closed.

**Comment by felixdrp** [comment]
Try to update the Chrome Browser.
